apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewer-binding
  namespace: vehicle
subjects:
  - kind: ServiceAccount
    name: viewer-sa
    namespace: vehicle
roleRef:
  kind: Role
  name: viewer-role
  apiGroup: rbac.authorization.k8s.io